unit Correspond;

interface
uses Init,MathMy;

procedure CorrespondParametersToTheForm;
procedure DisableSpinEdits;

implementation
uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  StdCtrls, ComCtrls, ExtCtrls,
  Unit1,Unit3,Unit4,Unit8,Unit10,ph_Dens,ph_Volt,HH_canal;

procedure CorrespondParametersToTheForm;
var  k :integer;
begin
  Form1.Smpl1 .Checked:=(Smpl=1);
  Form1.Smpl2 .Checked:=(Smpl=2);
  Form1.Smpl3 .Checked:=(Smpl=3);
  Form1.Smpl4 .Checked:=(Smpl=4);
  Form1.Smpl5 .Checked:=(Smpl=5);
  Form1.Smpl6 .Checked:=(Smpl=6);
  Form1.Smpl7 .Checked:=(Smpl=7);
  Form1.Smpl8 .Checked:=(Smpl=8);
  Form1.Smpl9 .Checked:=(Smpl=9);
  Form1.Smpl10.Checked:=(Smpl=10);
  Form1.Smpl11.Checked:=(Smpl=11);
  Form1.Smpl12.Checked:=(Smpl=12);
  Form1.Smpl13.Checked:=(Smpl=13);
  Form1.Smpl14.Checked:=(Smpl=14);
  Form1.Smpl15.Checked:=(Smpl=15);
  Form1.Smpl16.Checked:=(Smpl=16);
  Form1.Smpl17.Checked:=(Smpl=17);
  Form1.Smpl18.Checked:=(Smpl=18);
  Form1.Smpl19.Checked:=(Smpl=19);
  if NSmpls<>0 then begin
     if NSmpls<2 then  Form1.Smpl2.Enabled:=False;
     if NSmpls<3 then  Form1.Smpl3.Enabled:=False;
     if NSmpls<4 then  Form1.Smpl4.Enabled:=False;
     if NSmpls<5 then  Form1.Smpl5.Enabled:=False;
     if NSmpls<6 then  Form1.Smpl6.Enabled:=False;
     if NSmpls<7 then  Form1.Smpl7.Enabled:=False;
     if NSmpls<8 then  Form1.Smpl8.Enabled:=False;
     if NSmpls<9 then  Form1.Smpl9.Enabled:=False;
     if NSmpls<10 then  Form1.Smpl10.Enabled:=False;
     if NSmpls<11 then  Form1.Smpl11.Enabled:=False;
     if NSmpls<12 then  Form1.Smpl12.Enabled:=False;
     if NSmpls<13 then  Form1.Smpl13.Enabled:=False;
     if NSmpls<14 then  Form1.Smpl14.Enabled:=False;
     if NSmpls<15 then  Form1.Smpl15.Enabled:=False;
     if NSmpls<16 then  Form1.Smpl16.Enabled:=False;
     if NSmpls<17 then  Form1.Smpl17.Enabled:=False;
     if NSmpls<18 then  Form1.Smpl18.Enabled:=False;
     if NSmpls<19 then  Form1.Smpl19.Enabled:=False;
  end;
  //k:=i3_ie(i3);
  if HH_order[1]='1-point'  then  Form1.N1point1. Checked:=true;
  if HH_order[1]='2-points' then  Form1.N2points1.Checked:=true;
  if HH_order[2]='1-point'  then  Form1.N1point2. Checked:=true;
  if HH_order[2]='2-points' then  Form1.N2points2.Checked:=true;
  if HH_type[1]='Passive'   then  Form1.Passive1. Checked:=true;
  if HH_type[1]='Calmar'    then  Form1.Calmar1.  Checked:=true;
  if HH_type[1]='Destexhe'  then  Form1.Destexhe1.Checked:=true;
  if HH_type[1]='Migliore'  then  Form1.Migliore1.Checked:=true;
  if HH_type[1]='Chow'      then  Form1.Chow1.Checked:=true;
  if HH_type[1]='Lyle'      then  Form1.Lyle1.Checked:=true;
  if HH_type[2]='Passive'   then  Form1.Passive2. Checked:=true;
  if HH_type[2]='Calmar'    then  Form1.Calmar2.  Checked:=true;
  if HH_type[2]='Chow'      then  Form1.Chow2.Checked:=true;
  Form1.CheckBox4.Checked  :=(WriteOrNot=1);
  Form1.CheckBox6.Checked  :=(YesToClean=1);
  Form1.TVDscheme1.Checked :=(IfSecondOrder=1);
  Form1.ComboBox1.ItemIndex:=If_I_V_or_p-1;

  { Form4 }
  Form10.DDSpinEdit42.Value:=Vrest[3]*1e3;
  Form4.DDSpinEdit42.Value :=Vrest[3]*1e3;
  Form4.DDSpinEdit43.Value:=dt*1000;
  Form10.DDSpinEdit1.Value:=Iext;
  Form4.DDSpinEdit1.Value :=Iext;
  Form4.DDSpinEdit2.Value :=Square[1]*1e5;
  Form10.DDSpinEdit3.Value:=tSt*1000;
  Form4.DDSpinEdit3.Value :=tSt*1000;
  Form4.DDSpinEdit4.Value :=gAMPA[1];
  Form4.DDSpinEdit5.Value :=ThrCorrection[1]*1000;
  Form4.DDSpinEdit6.Value :=tauNoise*1000;
  Form10.DDSpinEdit2.Value:=t_end*1000;
  Form4.DDSpinEdit7.Value :=t_end*1000;
  Form4.DDSpinEdit8.Value :=gAMP3[1];
  Form4.DDSpinEdit9.Value:=gGABA[1];
  Form4.DDSpinEdit10.Value:=gGABB[1];
  Form4.DDSpinEdit11.Value:=gAMP3[2];
  Form4.DDSpinEdit12.Value:=gAMPA[2];
  Form4.DDSpinEdit13.Value:=gGABA[2];
  Form4.DDSpinEdit14.Value:=gGABB[2];
  Form4.DDSpinEdit15.Value:=gGAB3[1];
  Form4.DDSpinEdit16.Value:=gGAB3[2];
  Form4.DDSpinEdit17.Value:=gNMDA[1];
  Form4.DDSpinEdit18.Value:=gNMDA[2];
  Form4.DDSpinEdit19.Value:=gNMD3[1];
  Form4.DDSpinEdit20.Value:=gNMD3[2];
  Form4.DDSpinEdit21.Value:=Qns;
  { Time constants }
  Form4.DDSpinEdit22.Value:=alAMPA[1];
  Form4.DDSpinEdit23.Value:=alNMDA[1];
  Form4.DDSpinEdit24.Value:=alGABA[1];
  Form4.DDSpinEdit25.Value:=alGABB[1];
  Form4.DDSpinEdit26.Value:=beAMPA[1];
  Form4.DDSpinEdit27.Value:=beNMDA[1];
  Form4.DDSpinEdit28.Value:=beGABA[1];
  Form4.DDSpinEdit29.Value:=beGABB[1];
  Form4.DDSpinEdit30.Value:=alAMPA[2];
  Form4.DDSpinEdit31.Value:=alNMDA[2];
  Form4.DDSpinEdit32.Value:=alGABA[2];
  Form4.DDSpinEdit33.Value:=alGABB[2];
  Form4.DDSpinEdit34.Value:=beAMPA[2];
  Form4.DDSpinEdit35.Value:=beNMDA[2];
  Form4.DDSpinEdit36.Value:=beGABA[2];
  Form4.DDSpinEdit37.Value:=beGABB[2];
  Form4.DDSpinEdit38.Value:=VAMPA*1e3;
  Form4.DDSpinEdit39.Value:=VNMDA*1e3;
  Form4.DDSpinEdit40.Value:=VGABA*1e3;
  Form4.DDSpinEdit41.Value:=VGABB*1e3;
  Form4.DDSpinEdit44.Value:=Mg;
  Form4.DDSpinEdit45.Value:=roE;
  Form4.DDSpinEdit46.Value:=I_ind;
  Form4.DDSpinEdit47.Value:=nu_ind;
  Form4.DDSpinEdit48.Value:=t_ind*1e3;
  Form4.DDSpinEdit49.Value:=Vrest[1]*1e3;
  Form4.DDSpinEdit50.Value:=Vrest[2]*1e3;
  Form4.DDSpinEdit51.Value:=tau_m[1]*1e3;
  Form4.DDSpinEdit52.Value:=tau_m[2]*1e3;
  Form4.DDSpinEdit53.Value:=ThrCorrection[2]*1e3;
  Form4.DDSpinEdit54.Value:=Square[2]*1e5;
  Form4.DDSpinEdit55.Value:=sgm_V[1]*1000;
  Form4.DDSpinEdit73.Value:=sgm_V[2]*1000;
  Form4.DDSpinEdit56.Value:=gAHP[1];
  Form4.DDSpinEdit57.Value:=gAHP[2];
  Form4.DDSpinEdit58.Value:=gam[1];
  Form4.DDSpinEdit59.Value:=gam[2];
  Form4.DDSpinEdit60.Value:=gBst[1];
  Form4.DDSpinEdit61.Value:=gBst[2];
  Form4.DDSpinEdit62.Value:=tau_Bst;
  Form4.DDSpinEdit63.Value:=Nts;
  Form4.DDSpinEdit64.Value:=ts_end*1000;
  Form4.DDSpinEdit65.Value:=gGJ_I[2];
  Form4.DDSpinEdit67.Value:=dtSt*1000;
  Form4.DDSpinEdit68.Value:=gNaP[1];
  Form4.DDSpinEdit69.Value:=gNaP[2];
  Form4.DDSpinEdit70.Value:=NoiseToSgn;
  Form4.DDSpinEdit71.Value:=n_show;
  Form4.DDSpinEdit72.Value:=PlotWindow;
  Form4.DDSpinEdit74.Value:=gKM[1];
  Form4.DDSpinEdit80.Value:=n_DrawPhase;
  Form4.DDSpinEdit81.Value:=n_Write;
  Form4.DDSpinEdit83.Value:=Vreset[1]*1e3;
  Form4.DDSpinEdit84.Value:=Vreset[2]*1e3;
  Form4.DDSpinEdit85.Value:=gKA[1];
  Form4.DDSpinEdit86.Value:=gKA[2];
  Form4.DDSpinEdit87.Value:=gK[1];
  Form4.DDSpinEdit88.Value:=gK[2];
  Form4.DDSpinEdit89.Value:=factorI;
  Form4.DDSpinEdit91.Value:=pext_Iext;
  Form4.DDSpinEdit92.Value:=factorE;
  Form4.DDSpinEdit93.Value:=t0s*1e3;
  Form4.DDSpinEdit94.Value:=nStimuli;
  Form4.DDSpinEdit95.Value:=dt_T*1e3;
  Form4.DDSpinEdit96.Value:=C_membr[1]*1e3;
  Form4.DDSpinEdit97.Value:=C_membr[2]*1e3;
  Form4.DDSpinEdit99.Value:=gAMP3[3];
  Form4.DDSpinEdit100.Value:=gNMD3[3];
  Form4.DDSpinEdit101.Value:=gGAB3[3];
  Form4.DDSpinEdit102.Value:=gAMPA[3];
  Form4.DDSpinEdit103.Value:=gNMDA[3];
  Form4.DDSpinEdit104.Value:=gGABA[3];
  Form4.DDSpinEdit105.Value:=gGABB[3];
  Form10.CheckBox1.Checked:=(IfBlockAMPA=1);
  Form10.CheckBox2.Checked:=(IfBlockNMDA=1);
  Form10.CheckBox3.Checked:=(IfBlockGABA=1);
  Form10.CheckBox4.Checked:=(IfBlockGABB=1);
  Form4.CheckBox1.Checked:=(IfBlockAMPA=1);
  Form4.CheckBox2.Checked:=(IfBlockNMDA=1);
  Form4.CheckBox3.Checked:=(IfBlockGABA=1);
  Form4.CheckBox4.Checked:=(IfBlockGABB=1);
  Form4.CheckBox5.Checked:=(IfInSyn_al_EQ_beta=1);
  Form4.CheckBox6.Checked:=(IfBlockK=1);
  Form4.CheckBox15.Checked:=(IfSigmoidForPresynRate=1);
  Form4.CheckBox16.Checked:=(IfEqForVGABA=1);
  if i3=1 then Form4.i3_Combo.ItemIndex:=0;
  if i3=2 then Form4.i3_Combo.ItemIndex:=1;
  Form10.RadioGroup1.ItemIndex:=i3-1;
  Form10.RadioGroup2.ItemIndex:=i3-1;
  { Disable SpinEdits }
  DisableSpinEdits;
  {--- for 2D: }
  Form3.DDSpinEdit1.Value:=ni;
  Form3.DDSpinEdit2.Value:=nj;
  Form3.DDSpinEdit4.Value:=R_stim;
  Form3.DDSpinEdit5.Value:=ni_stim;
  Form3.DDSpinEdit6.Value:=nj_stim;
  Form3.DDSpinEdit7.Value:=dt_out*1000;
  if a_axon[1]*dt>0 then Form3.DDSpinEdit8.Value:=round(dx/a_axon[1]/dt);
  if a_axon[1]*dt>0 then Form3.DDSpinEdit9.Value:=round(dy/a_axon[1]/dt);
  Form3.DDSpinEdit10.Value:=i_view;
  Form3.DDSpinEdit11.Value:=j_view;
  {--- for V1: }
  Form8.DDSpinEdit1.Value:=ni;
  Form8.DDSpinEdit4.Value:=R_stim;
  Form8.DDSpinEdit5.Value:=X_stim/pi*180;
end;

procedure DisableSpinEdits;
var OK :boolean;
begin
  with Form4 do begin
    OK:=CheckBox11.Checked; {On/Off for REGISTERED CELL }
    DDSpinEdit99.Enabled:=OK;
    DDSpinEdit100.Enabled:=OK;
    DDSpinEdit101.Enabled:=OK;
    DDSpinEdit102.Enabled:=OK;
    DDSpinEdit103.Enabled:=OK;
    DDSpinEdit104.Enabled:=OK;
    DDSpinEdit105.Enabled:=OK;
    OK:=not(IfBlockAMPA=1);
    DDSpinEdit8 .Enabled:=OK;
    DDSpinEdit11.Enabled:=OK;
    DDSpinEdit4 .Enabled:=OK;
    DDSpinEdit12.Enabled:=OK;
    DDSpinEdit22.Enabled:=OK;
    DDSpinEdit26.Enabled:=OK;
    DDSpinEdit30.Enabled:=OK;
    DDSpinEdit34.Enabled:=OK;
    DDSpinEdit38.Enabled:=OK;
    DDSpinEdit99.Enabled:=OK;
    DDSpinEdit102.Enabled:=OK;
    OK:=not(IfBlockNMDA=1);
    DDSpinEdit19.Enabled:=OK;
    DDSpinEdit20.Enabled:=OK;
    DDSpinEdit17.Enabled:=OK;
    DDSpinEdit18.Enabled:=OK;
    DDSpinEdit23.Enabled:=OK;
    DDSpinEdit27.Enabled:=OK;
    DDSpinEdit31.Enabled:=OK;
    DDSpinEdit35.Enabled:=OK;
    DDSpinEdit39.Enabled:=OK;
    DDSpinEdit100.Enabled:=OK;
    DDSpinEdit103.Enabled:=OK;
    OK:=not(IfBlockGABA=1);
    DDSpinEdit15.Enabled:=OK;
    DDSpinEdit16.Enabled:=OK;
    DDSpinEdit9 .Enabled:=OK;
    DDSpinEdit13.Enabled:=OK;
    DDSpinEdit24.Enabled:=OK;
    DDSpinEdit28.Enabled:=OK;
    DDSpinEdit32.Enabled:=OK;
    DDSpinEdit36.Enabled:=OK;
    DDSpinEdit40.Enabled:=OK;
    DDSpinEdit101.Enabled:=OK;
    DDSpinEdit104.Enabled:=OK;
    OK:=not(IfBlockGABB=1);
    DDSpinEdit10.Enabled:=OK;
    DDSpinEdit14.Enabled:=OK;
    DDSpinEdit25.Enabled:=OK;
    DDSpinEdit29.Enabled:=OK;
    DDSpinEdit33.Enabled:=OK;
    DDSpinEdit37.Enabled:=OK;
    DDSpinEdit41.Enabled:=OK;
    DDSpinEdit105.Enabled:=OK;
    OK:=not(IfInSyn_al_EQ_beta=1);
    DDSpinEdit26.Enabled:=(OK and not(IfBlockAMPA=1));
    DDSpinEdit27.Enabled:=(OK and not(IfBlockNMDA=1));
    DDSpinEdit28.Enabled:=(OK and not(IfBlockGABA=1));
    DDSpinEdit29.Enabled:=(OK and not(IfBlockGABB=1));
    DDSpinEdit34.Enabled:=(OK and not(IfBlockAMPA=1));
    DDSpinEdit35.Enabled:=(OK and not(IfBlockNMDA=1));
    DDSpinEdit36.Enabled:=(OK and not(IfBlockGABA=1));
    DDSpinEdit37.Enabled:=(OK and not(IfBlockGABB=1));
    DDSpinEdit45.Enabled:=(HH_order[1]='2-points');
    DDSpinEdit56.Enabled:=not(HH_type[1]='Passive');
    DDSpinEdit57.Enabled:=not(HH_type[2]='Passive');
    DDSpinEdit60.Enabled:=not(HH_type[1]='Passive');
    DDSpinEdit61.Enabled:=not(HH_type[2]='Passive');
    DDSpinEdit68.Enabled:=not(HH_type[1]='Passive');
    DDSpinEdit69.Enabled:=not(HH_type[2]='Passive');
    DDSpinEdit74.Enabled:=not(HH_type[1]='Passive');
    DDSpinEdit62.Enabled:=not(HH_type[1]='Passive');
    DDSpinEdit83.Enabled:=(HH_type[1]='Passive');
    DDSpinEdit84.Enabled:=(HH_type[2]='Passive');
    DDSpinEdit85.Enabled:=not((HH_type[1]='Passive')or(IfBlockK=1));
    DDSpinEdit86.Enabled:=not((HH_type[2]='Passive')or(IfBlockK=1));
    DDSpinEdit87.Enabled:=not((HH_type[1]='Passive')or(IfBlockK=1));
    DDSpinEdit88.Enabled:=not((HH_type[2]='Passive')or(IfBlockK=1));
    DDSpinEdit89.Enabled:=(IfSigmoidForPresynRate=1);
    OK:=(IfEqForVGABA=1);
    DDSpinEdit75.Enabled:=OK;
    DDSpinEdit76.Enabled:=OK;
    DDSpinEdit77.Enabled:=OK;
    DDSpinEdit78.Enabled:=OK;
    DDSpinEdit79.Enabled:=OK;
  end;
end;

end.
